//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.06 at 10:11:56 AM CST 
//


package chow.dan.mpd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProgramInformation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="moreInformationURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Period">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AdaptationSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Representation" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SegmentList">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Initialization">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="sourceURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="SegmentURL" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;attribute name="media" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="timescale" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                                               &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                                     &lt;attribute name="mimeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="codecs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                                     &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                                     &lt;attribute name="frameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                                     &lt;attribute name="sar" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="startWithSAP" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                                     &lt;attribute name="bandwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="segmentAlignment" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="maxWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                           &lt;attribute name="maxHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *                           &lt;attribute name="maxFrameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                           &lt;attribute name="par" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="minBufferTime" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mediaPresentationDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="maxSegmentDuration" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="profiles" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "programInformation",
    "period"
})
@XmlRootElement(name = "MPD")
public class MPD {

    @XmlElement(name = "ProgramInformation", required = true)
    protected MPD.ProgramInformation programInformation;
    @XmlElement(name = "Period", required = true)
    protected MPD.Period period;
    @XmlAttribute(name = "minBufferTime", required = true)
    protected Duration minBufferTime;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "mediaPresentationDuration", required = true)
    protected Duration mediaPresentationDuration;
    @XmlAttribute(name = "maxSegmentDuration", required = true)
    protected Duration maxSegmentDuration;
    @XmlAttribute(name = "profiles", required = true)
    protected String profiles;

    /**
     * Gets the value of the programInformation property.
     * 
     * @return
     *     possible object is
     *     {@link MPD.ProgramInformation }
     *     
     */
    public MPD.ProgramInformation getProgramInformation() {
        return programInformation;
    }

    /**
     * Sets the value of the programInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MPD.ProgramInformation }
     *     
     */
    public void setProgramInformation(MPD.ProgramInformation value) {
        this.programInformation = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link MPD.Period }
     *     
     */
    public MPD.Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link MPD.Period }
     *     
     */
    public void setPeriod(MPD.Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the minBufferTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMinBufferTime() {
        return minBufferTime;
    }

    /**
     * Sets the value of the minBufferTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMinBufferTime(Duration value) {
        this.minBufferTime = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the mediaPresentationDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMediaPresentationDuration() {
        return mediaPresentationDuration;
    }

    /**
     * Sets the value of the mediaPresentationDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMediaPresentationDuration(Duration value) {
        this.mediaPresentationDuration = value;
    }

    /**
     * Gets the value of the maxSegmentDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getMaxSegmentDuration() {
        return maxSegmentDuration;
    }

    /**
     * Sets the value of the maxSegmentDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaxSegmentDuration(Duration value) {
        this.maxSegmentDuration = value;
    }

    /**
     * Gets the value of the profiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfiles() {
        return profiles;
    }

    /**
     * Sets the value of the profiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfiles(String value) {
        this.profiles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AdaptationSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Representation" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SegmentList">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Initialization">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="sourceURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="SegmentURL" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;attribute name="media" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="timescale" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                                     &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *                           &lt;attribute name="mimeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="codecs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                           &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                           &lt;attribute name="frameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *                           &lt;attribute name="sar" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="startWithSAP" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *                           &lt;attribute name="bandwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="segmentAlignment" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="maxWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                 &lt;attribute name="maxHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
     *                 &lt;attribute name="maxFrameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *                 &lt;attribute name="par" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adaptationSet"
    })
    public static class Period {

        @XmlElement(name = "AdaptationSet", required = true)
        protected MPD.Period.AdaptationSet adaptationSet;
        @XmlAttribute(name = "duration", required = true)
        protected Duration duration;

        /**
         * Gets the value of the adaptationSet property.
         * 
         * @return
         *     possible object is
         *     {@link MPD.Period.AdaptationSet }
         *     
         */
        public MPD.Period.AdaptationSet getAdaptationSet() {
            return adaptationSet;
        }

        /**
         * Sets the value of the adaptationSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link MPD.Period.AdaptationSet }
         *     
         */
        public void setAdaptationSet(MPD.Period.AdaptationSet value) {
            this.adaptationSet = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        public Duration getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        public void setDuration(Duration value) {
            this.duration = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Representation" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SegmentList">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Initialization">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="sourceURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="SegmentURL" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;attribute name="media" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="timescale" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *                           &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
         *                 &lt;attribute name="mimeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="codecs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *                 &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *                 &lt;attribute name="frameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
         *                 &lt;attribute name="sar" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="startWithSAP" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
         *                 &lt;attribute name="bandwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="segmentAlignment" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="maxWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *       &lt;attribute name="maxHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
         *       &lt;attribute name="maxFrameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
         *       &lt;attribute name="par" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "representation"
        })
        public static class AdaptationSet {

            @XmlElement(name = "Representation", required = true)
            protected List<MPD.Period.AdaptationSet.Representation> representation;
            @XmlAttribute(name = "segmentAlignment", required = true)
            protected boolean segmentAlignment;
            @XmlAttribute(name = "maxWidth", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected int maxWidth;
            @XmlAttribute(name = "maxHeight", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected int maxHeight;
            @XmlAttribute(name = "maxFrameRate", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short maxFrameRate;
            @XmlAttribute(name = "par", required = true)
            protected String par;
            @XmlAttribute(name = "lang", required = true)
            protected String lang;

            /**
             * Gets the value of the representation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the representation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRepresentation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MPD.Period.AdaptationSet.Representation }
             * 
             * 
             */
            public List<MPD.Period.AdaptationSet.Representation> getRepresentation() {
                if (representation == null) {
                    representation = new ArrayList<MPD.Period.AdaptationSet.Representation>();
                }
                return this.representation;
            }

            /**
             * Gets the value of the segmentAlignment property.
             * 
             */
            public boolean isSegmentAlignment() {
                return segmentAlignment;
            }

            /**
             * Sets the value of the segmentAlignment property.
             * 
             */
            public void setSegmentAlignment(boolean value) {
                this.segmentAlignment = value;
            }

            /**
             * Gets the value of the maxWidth property.
             * 
             */
            public int getMaxWidth() {
                return maxWidth;
            }

            /**
             * Sets the value of the maxWidth property.
             * 
             */
            public void setMaxWidth(int value) {
                this.maxWidth = value;
            }

            /**
             * Gets the value of the maxHeight property.
             * 
             */
            public int getMaxHeight() {
                return maxHeight;
            }

            /**
             * Sets the value of the maxHeight property.
             * 
             */
            public void setMaxHeight(int value) {
                this.maxHeight = value;
            }

            /**
             * Gets the value of the maxFrameRate property.
             * 
             */
            public short getMaxFrameRate() {
                return maxFrameRate;
            }

            /**
             * Sets the value of the maxFrameRate property.
             * 
             */
            public void setMaxFrameRate(short value) {
                this.maxFrameRate = value;
            }

            /**
             * Gets the value of the par property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPar() {
                return par;
            }

            /**
             * Sets the value of the par property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPar(String value) {
                this.par = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SegmentList">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Initialization">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="sourceURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="SegmentURL" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;attribute name="media" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="timescale" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
             *                 &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
             *       &lt;attribute name="mimeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="codecs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="width" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
             *       &lt;attribute name="height" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
             *       &lt;attribute name="frameRate" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
             *       &lt;attribute name="sar" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="startWithSAP" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
             *       &lt;attribute name="bandwidth" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "segmentList"
            })
            public static class Representation {

                @XmlElement(name = "SegmentList", required = true)
                protected MPD.Period.AdaptationSet.Representation.SegmentList segmentList;
                @XmlAttribute(name = "id", required = true)
                @XmlSchemaType(name = "unsignedByte")
                protected short id;
                @XmlAttribute(name = "mimeType", required = true)
                protected String mimeType;
                @XmlAttribute(name = "codecs", required = true)
                protected String codecs;
                @XmlAttribute(name = "width", required = true)
                @XmlSchemaType(name = "unsignedShort")
                protected int width;
                @XmlAttribute(name = "height", required = true)
                @XmlSchemaType(name = "unsignedShort")
                protected int height;
                @XmlAttribute(name = "frameRate", required = true)
                @XmlSchemaType(name = "unsignedByte")
                protected short frameRate;
                @XmlAttribute(name = "sar", required = true)
                protected String sar;
                @XmlAttribute(name = "startWithSAP", required = true)
                @XmlSchemaType(name = "unsignedByte")
                protected short startWithSAP;
                @XmlAttribute(name = "bandwidth", required = true)
                @XmlSchemaType(name = "unsignedInt")
                protected long bandwidth;

                /**
                 * Gets the value of the segmentList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MPD.Period.AdaptationSet.Representation.SegmentList }
                 *     
                 */
                public MPD.Period.AdaptationSet.Representation.SegmentList getSegmentList() {
                    return segmentList;
                }

                /**
                 * Sets the value of the segmentList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MPD.Period.AdaptationSet.Representation.SegmentList }
                 *     
                 */
                public void setSegmentList(MPD.Period.AdaptationSet.Representation.SegmentList value) {
                    this.segmentList = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public short getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setId(short value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the mimeType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMimeType() {
                    return mimeType;
                }

                /**
                 * Sets the value of the mimeType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMimeType(String value) {
                    this.mimeType = value;
                }

                /**
                 * Gets the value of the codecs property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCodecs() {
                    return codecs;
                }

                /**
                 * Sets the value of the codecs property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCodecs(String value) {
                    this.codecs = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 */
                public int getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 */
                public void setWidth(int value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 */
                public int getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 */
                public void setHeight(int value) {
                    this.height = value;
                }

                /**
                 * Gets the value of the frameRate property.
                 * 
                 */
                public short getFrameRate() {
                    return frameRate;
                }

                /**
                 * Sets the value of the frameRate property.
                 * 
                 */
                public void setFrameRate(short value) {
                    this.frameRate = value;
                }

                /**
                 * Gets the value of the sar property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSar() {
                    return sar;
                }

                /**
                 * Sets the value of the sar property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSar(String value) {
                    this.sar = value;
                }

                /**
                 * Gets the value of the startWithSAP property.
                 * 
                 */
                public short getStartWithSAP() {
                    return startWithSAP;
                }

                /**
                 * Sets the value of the startWithSAP property.
                 * 
                 */
                public void setStartWithSAP(short value) {
                    this.startWithSAP = value;
                }

                /**
                 * Gets the value of the bandwidth property.
                 * 
                 */
                public long getBandwidth() {
                    return bandwidth;
                }

                /**
                 * Sets the value of the bandwidth property.
                 * 
                 */
                public void setBandwidth(long value) {
                    this.bandwidth = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Initialization">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="sourceURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="SegmentURL" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;attribute name="media" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="timescale" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
                 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "initialization",
                    "segmentURL"
                })
                public static class SegmentList {

                    @XmlElement(name = "Initialization", required = true)
                    protected MPD.Period.AdaptationSet.Representation.SegmentList.Initialization initialization;
                    @XmlElement(name = "SegmentURL", required = true)
                    protected List<MPD.Period.AdaptationSet.Representation.SegmentList.SegmentURL> segmentURL;
                    @XmlAttribute(name = "timescale", required = true)
                    @XmlSchemaType(name = "unsignedShort")
                    protected int timescale;
                    @XmlAttribute(name = "duration", required = true)
                    @XmlSchemaType(name = "unsignedShort")
                    protected int duration;

                    /**
                     * Gets the value of the initialization property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link MPD.Period.AdaptationSet.Representation.SegmentList.Initialization }
                     *     
                     */
                    public MPD.Period.AdaptationSet.Representation.SegmentList.Initialization getInitialization() {
                        return initialization;
                    }

                    /**
                     * Sets the value of the initialization property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link MPD.Period.AdaptationSet.Representation.SegmentList.Initialization }
                     *     
                     */
                    public void setInitialization(MPD.Period.AdaptationSet.Representation.SegmentList.Initialization value) {
                        this.initialization = value;
                    }

                    /**
                     * Gets the value of the segmentURL property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the segmentURL property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getSegmentURL().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link MPD.Period.AdaptationSet.Representation.SegmentList.SegmentURL }
                     * 
                     * 
                     */
                    public List<MPD.Period.AdaptationSet.Representation.SegmentList.SegmentURL> getSegmentURL() {
                        if (segmentURL == null) {
                            segmentURL = new ArrayList<MPD.Period.AdaptationSet.Representation.SegmentList.SegmentURL>();
                        }
                        return this.segmentURL;
                    }

                    /**
                     * Gets the value of the timescale property.
                     * 
                     */
                    public int getTimescale() {
                        return timescale;
                    }

                    /**
                     * Sets the value of the timescale property.
                     * 
                     */
                    public void setTimescale(int value) {
                        this.timescale = value;
                    }

                    /**
                     * Gets the value of the duration property.
                     * 
                     */
                    public int getDuration() {
                        return duration;
                    }

                    /**
                     * Sets the value of the duration property.
                     * 
                     */
                    public void setDuration(int value) {
                        this.duration = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="sourceURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Initialization {

                        @XmlAttribute(name = "sourceURL", required = true)
                        protected String sourceURL;

                        /**
                         * Gets the value of the sourceURL property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSourceURL() {
                            return sourceURL;
                        }

                        /**
                         * Sets the value of the sourceURL property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSourceURL(String value) {
                            this.sourceURL = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;attribute name="media" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class SegmentURL {

                        @XmlAttribute(name = "media", required = true)
                        protected String media;

                        /**
                         * Gets the value of the media property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getMedia() {
                            return media;
                        }

                        /**
                         * Sets the value of the media property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setMedia(String value) {
                            this.media = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="moreInformationURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title"
    })
    public static class ProgramInformation {

        @XmlElement(name = "Title", required = true)
        protected String title;
        @XmlAttribute(name = "moreInformationURL", required = true)
        protected String moreInformationURL;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the moreInformationURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMoreInformationURL() {
            return moreInformationURL;
        }

        /**
         * Sets the value of the moreInformationURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMoreInformationURL(String value) {
            this.moreInformationURL = value;
        }

    }

}
